version = 0.1

[default.deploy.parameters]
stack_name = "identityapistack"
s3_bucket = "identitybucket-dev-eu-west-3-deploy"
s3_prefix = "identityapistack"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []